<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWtcxZg1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWtcxZg1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWtcxZg1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWtcxZg1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWtcxZg1\App_KernelDevDebugContainer([
    'container.build_hash' => 'WtcxZg1',
    'container.build_id' => '62d696ab',
    'container.build_time' => 1652792329,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWtcxZg1');
