<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW5jIa2a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW5jIa2a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW5jIa2a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW5jIa2a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW5jIa2a\App_KernelDevDebugContainer([
    'container.build_hash' => 'W5jIa2a',
    'container.build_id' => '3b5e4285',
    'container.build_time' => 1652886872,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW5jIa2a');
