<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS3XSqo8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS3XSqo8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS3XSqo8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS3XSqo8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS3XSqo8\App_KernelDevDebugContainer([
    'container.build_hash' => 'S3XSqo8',
    'container.build_id' => '6487943c',
    'container.build_time' => 1652859389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS3XSqo8');
