<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_bootstrap' => [[], ['_controller' => 'App\\Controller\\BootstrapController::index'], [], [['text', '/bootstrap']], [], []],
    'exo_index' => [['name'], ['_controller' => 'App\\Controller\\ExoController::index'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/exo/candidat']], [], []],
    'exo_get_numero_secu_sociale' => [['numeroSecuriteSociale'], ['_controller' => 'App\\Controller\\ExoController::getNumeroSecuriteSociale'], ['numeroSecuriteSociale' => '\\d+'], [['variable', '/', '\\d+', 'numeroSecuriteSociale', true], ['text', '/exo/candidat/numero']], [], []],
    'exo_loto' => [['min', 'max'], ['_controller' => 'App\\Controller\\ExoController::loto'], [], [['variable', '/', '[^/]++', 'max', true], ['variable', '/', '[^/]++', 'min', true], ['text', '/exo/loto']], [], []],
    'exo_alphabet' => [[], ['_controller' => 'App\\Controller\\ExoController::tableauAlphabet'], [], [['text', '/exo/alphabet']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\QuoteController::index'], [], [['text', '/']], [], []],
];
