<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app_bootstrap' => [[], ['_controller' => 'App\\Controller\\BootstrapController::index'], [], [['text', '/bootstrap']], [], []],
    'exo_index' => [['name'], ['_controller' => 'App\\Controller\\ExoController::index'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/exo/candidat']], [], []],
    'exo_get_numero_secu_sociale' => [['numeroSecuriteSociale'], ['_controller' => 'App\\Controller\\ExoController::getNumeroSecuriteSociale'], ['numeroSecuriteSociale' => '\\d+'], [['variable', '/', '\\d+', 'numeroSecuriteSociale', true], ['text', '/exo/candidat/numero']], [], []],
    'exo_loto' => [['min', 'max'], ['_controller' => 'App\\Controller\\ExoController::loto'], [], [['variable', '/', '[^/]++', 'max', true], ['variable', '/', '[^/]++', 'min', true], ['text', '/exo/loto']], [], []],
    'exo_alphabet' => [[], ['_controller' => 'App\\Controller\\ExoController::tableauAlphabet'], [], [['text', '/exo/alphabet']], [], []],
    'app_product_index' => [[], ['_controller' => 'App\\Controller\\ProductController::index'], [], [['text', '/product/']], [], []],
    'app_product_new' => [[], ['_controller' => 'App\\Controller\\ProductController::new'], [], [['text', '/product/new']], [], []],
    'app_product_show' => [['id'], ['_controller' => 'App\\Controller\\ProductController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'app_product_edit' => [['id'], ['_controller' => 'App\\Controller\\ProductController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'app_product_delete' => [['id'], ['_controller' => 'App\\Controller\\ProductController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\QuoteController::index'], [], [['text', '/']], [], []],
];
