version: '3.8'

services:
  database:
    container_name: database-jour2
    image: mysql:8.0
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4307:3307'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php-jour2
    build:
      context: ./php
    ports:
      - '9001:9001'
    volumes:
      - ./app:/var/www/symfony_docker
    depends_on:
      - database
  nginx:
    container_name: nginx-jour2
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  phpmyadmin:
    container_name: phpmyadmin-jour2
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1